#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2020 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse

import pikepdf

def unparse_arg(arg):
    if isinstance(arg, pikepdf.objects.Object):
        return arg.unparse()
    else:
        return str(arg).encode()

def unparse(args, op):
    return b' '.join(unparse_arg(arg) for arg in args) + b' ' + op.unparse()

def mangle_pdf(pdf):
    for page in pdf.pages:
        mangle_page(pdf, page)

def mangle_page(pdf, page):
    page.page_contents_coalesce()
    op_rg = pikepdf.Operator('rg')
    op_BT = pikepdf.Operator('BT')
    op_ET = pikepdf.Operator('ET')
    text_showing_ops = frozenset(map(pikepdf.Operator, {'TJ', 'Tj', '\'', '"'}))
    text_obj = False
    stream = []
    for args, op in pikepdf.parse_content_stream(page):
        if text_obj:
            if op in text_showing_ops:
                stream += [unparse((0, 0, 1), op_rg)]
            elif op == op_ET:
                text_obj = False
        elif op == op_BT:
            text_obj = True
        stream += [unparse(args, op)]
    stream = b'\n'.join(stream)
    page.Contents = pikepdf.Stream(pdf, stream)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('input', metavar='INPUT-FILE')
    ap.add_argument('output', metavar='OUTPUT-FILE')
    options = ap.parse_args()
    pdf = pikepdf.open(options.input)
    mangle_pdf(pdf)
    pdf.save(options.output)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
